/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    screens: {
      sm: '375px',
      md: '720px',
      dt: '1024px',
      lg: '1280px',
      xl: '1440px',
      '2xl': '1680px',
      '3xl': '1920px',
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-opensans)', ...fontFamily.sans],
        serif: ['var(--font-merriweather)', ...fontFamily.serif],
        montserrat: ['var(--font-montserrat)', ...fontFamily.sans],
        raleway: ['var(--font-raleway)', ...fontFamily.sans],
      },
      colors: {
        black: '#000000',
        white: '#ffffff',
        transparent: 'transparent',
        inherit: 'inherit',
        mineShaftBlack: '#222121',
        mystic: '#dde5e9',
        alto: '#d9d9d9',
        green: '#287d21',
        green2: '#357754',
        purple: '#240f6e',
        purple2: '#22096e',
        midPurple: '#3c1dad',
        lightPurple: '#a79fc5',
        lightPurple2: '#9264CD',
        red: '#e02f32',
        darkRed: '#97272C',
        orange: '#ED8B00',
        teal: '#00968F',
        navy: '#003764',
        lightBlue: '#E4F1FD',
        lightBlue2: '#c3e2ff',
        darkBlue: '#1662A4',
        maroon: '#6A1B1F',
        gray: '#8E9089',
        gray2: '#536171',
        darkGray: '#4a494e',
        darkGray2: '#3E3E3E',
        lightGray1: '#F4F4F4',
        lightGray2: '#CDCDCD',
        LightGray3: '#bebebe',
        horizontalGrayLine: '#6A6A6A',
        slantedGrayLine: '#FFFFFF4C', // 'rgba(255, 255, 255, 0.3)',
        slantedLightGrayLine: '#C0C0C0',
        regionNameGray: `#EDEDED`,
        iconBgGray: `#E2E2E2`,
        secondaryBlue: '#7CA0C5',
        secondaryYellow: '#FDD773',
        secondaryGreen: '#6DCB99',
        secondaryDarkBlue: '#236192',
        secondaryLightGray: '#707372',
      },
    },
  },
  plugins: [],
};
