/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './node_modules/tw-elements/dist/js/**/*.js',
  ],
  theme: {
    screens: {
      sm: '375px',
      md: '720px',
      dt: '1024px',
      lg: '1280px',
      xl: '1440px',
      '2xl': '1680px',
      '3xl': '1920px',
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-opensans)'],
        serif: ['var(--font-merriweather)'],
        montserrat: ['var(--font-montserrat)'],
        raleway: ['var(--font-raleway)'],
      },
      colors: {
        // black: '#000000',
        // white: '#ffffff',
        transparent: 'transparent',
        inherit: 'inherit',
        charcoal: '#121212',
        mineShaftBlack: '#222121',
        mystic: '#dde5e9',
        alto: '#d9d9d9',
        green: '#287d21',
        green2: '#357754',
        purple: '#240f6e',
        purple2: '#22096e',
        midPurple: '#3c1dad',
        lightPurple: '#a79fc5',
        lightPurple2: '#9264CD',
        red: '#e02f32',
        darkRed: '#97272C',
        orange: '#ED8B00',
        navy: '#003764',
        lightBlue: '#E4F1FD',
        lightBlue2: '#c3e2ff',
        darkBlue: '#1662A4',
        maroon: '#6A1B1F',
        // gray: '#8E9089',
        // gray2: '#536171',
        // darkGray: '#4a494e',
        // darkGray2: '#3E3E3E',
        // lightGray1: '#F4F4F4',
        // lightGray2: '#CDCDCD',
        // LightGray3: '#bebebe',
        horizontalGrayLine: '#6A6A6A',
        slantedGrayLine: '#FFFFFF4C', // 'rgba(255, 255, 255, 0.3)',
        slantedLightGrayLine: '#C0C0C0',
        regionNameGray: `#EDEDED`,
        iconBgGray: `#E2E2E2`,
        // secondaryBlue: '#7CA0C5',
        // secondaryYellow: '#FDD773',
        // secondaryGreen: '#6DCB99',
        // secondaryDarkBlue: '#236192',
        // secondaryLightGray: '#707372',
      },
      boxShadow: {
        custom: '0px 4px 4px rgba(0, 0, 0, 0.1)',
        'custom-2': '0px 0px 6px 2px rgba(0, 0, 0, 0.25)',
        'custom-3': '0px 4px 4px rgba(0, 0, 0, 0.25)',
        'custom-4': '0px 3px 6px -3px rgba(32, 33, 36, 0.28)',
      },
    },
  },
  plugins: [require('tw-elements/dist/plugin')],
};
